### ISSUE TITLE
Falha ao executar `pod install`

### ISSUE THREAD

**Issue by miguelarauj1o** [CocoaHeadsBrasil/CocoaHeadsApp#112]
Olá, após executar `pod install` no terminal, estou recebendo a seguinte saída:

``` zsh
[!] Your Podfile requires that the plugin `cocoapods-acknowledgements` be installed. Please install it and try installation again.
```

Não seria interessante instalar o plugin durante o setup?

**Comment by talesp** [comment]
@miguelarauj1o fiz uma alteração. Eu tive um problema com o setup inicial, foi preciso fazer um pod repo update para funcionar para mim, pois minha cópia local dos repositórios estavam desatualizados. Lembre-se também de usar o `bundler` e atualizar as dependências com `bundle exec pod install` ao invés de apenas `pod install`. Qualquer coisa avisa aqui :)
