### ISSUE TITLE
README: Estruturação do repositório - branches, tags, etc

### ISSUE THREAD

**Issue by barbosa** [CocoaHeadsBrasil/CocoaHeadsApp#20]

**Comment by Viniciuscarvalho** [comment]
@igorcferreira aquela estruturação que foi falada, poderia ser aplicada aqui e deixar o Workflow de contribuição dividido.

**Comment by igorcferreira** [comment]
@Viniciuscarvalho: Irei associar essa issue para mim e irei condensar o workflow aqui.

**Comment by Viniciuscarvalho** [comment]
Tudo certo então, vou retirar a outra issue de workflow, pra não ficar tão bagunçado.

**Comment by barbosa** [comment]
Te adicionei na #21, @igorcferreira 

Vou fechar essa porque o título da outra faz mais sentido.
