### ISSUE TITLE
README: Workflow de colaboração

### ISSUE THREAD

**Issue by barbosa** [CocoaHeadsBrasil/CocoaHeadsApp#21]

**Comment by Viniciuscarvalho** [comment]
Para contribuir devidamente com o projeto; fork (se não tiver um) -> branch -> alterações -> fetch/pull -> rebase master -> PR

Em seguida, através dos testes do Travis e também após uma revisão, a modificação é aceita.

**Comment by Viniciuscarvalho** [comment]
@barbosa Essa issue está duplicada, seria melhor deixar só uma de organização de branches e modo de contribuição, não é?

**Comment by barbosa** [comment]
@Viniciuscarvalho Sim. Vou fechar a outra. O título dessa aqui faz mais sentido.
