### ISSUE TITLE
README: Licença/Copyrights

### ISSUE THREAD

**Issue by barbosa** [CocoaHeadsBrasil/CocoaHeadsApp#22]

**Comment by barbosa** [comment]
Estava olhando algumas apps open source pra ver qual licença estão usando.

As da Artsy em geral são **MIT**: [eigen](https://github.com/artsy/eigen/blob/master/LICENSE), [eidolon](https://github.com/artsy/eidolon/blob/master/LICENSE) e [energy](https://github.com/artsy/energy/blob/master/LICENSE). A app do [Wikipedia](https://github.com/wikimedia/wikipedia-ios/blob/master/LICENSE.txt) também.

[VLC](https://github.com/videolan/vlc/blob/master/COPYING) e [Wordpress](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/LICENSE) usam **GPL v2**.

Iria sugerir usar MIT também. O que acham?

Alguma sugestão, @diogot?

**Comment by gfpoliva** [comment]
Temos que analisar as pequenas diferenças das duas:

| - | MIT | GPL v2 |
| --- | --- | --- |
| Exigido: | Aviso de licença e direitos autorais | Aviso de licença e direitos autorais, Mudanças de Estado e Aviso de licença e direitos autorais |
| Permitido: | Uso comercial, modificação, distribuição e sublicenciamento | Uso comercial, modificação, distribuição e concessão de patente |
| Proibido: | Reponsabilidade Assegurada | Reponsabilidade assegurada e sublicenciamento |

Como o @barbosa disse, também iria sugerir a licença MIT por ser permissiva e um pouco mais simples.

**Comment by jpros** [comment]
Vocês acham que deveria permitir uso comercial?

**Comment by gfpoliva** [comment]
@jpros todas as licenças open source permitem uso comercial.

**Comment by nobre84** [comment]
A grande diferença mesmo é que GPL é um buraco negro, qualquer coisa que tocar no código terá de se tornar GPL também. Isso limita seu uso em praticamente qualquer ambiente. O termo usado é copyleft.

Att
Rafael Nobre

**Comment by nobre84** [comment]
As viáveis na minha opinião são MIT e Apache 2.0, a diferença prática entre elas é que na Apache é necessário citar a utilização do código na documentação ou área about/legal do software final que utilizar. Na MIT isso é opcional, devendo apenas manter os headers originais que citam a licença e assinalar explicitamente modificações.

**Comment by gfpoliva** [comment]
Outra diferença entre as licenças Apache e MIT é que na Apache está explicito não poder utilizar nomes, logos, ou marcas de contribuidores.

Vejam o item 6:

> This License does not grant permission to use the trade names, trademarks,
> service marks, or product names of the Licensor, except as required for
> reasonable and customary use in describing the origin of the Work and
> reproducing the content of the NOTICE file.

**Comment by diogot** [comment]
Eu gosto da licença do MIT, foi esse que colocamos no [Un]MuteApp

**Comment by gfpoliva** [comment]
Licença do MIT adicionada.
