### ISSUE TITLE
README: Links e formas de contato

### ISSUE THREAD

**Issue by barbosa** [CocoaHeadsBrasil/CocoaHeadsApp#24]

**Comment by gfpoliva** [comment]
Formas de Contato:
- Twitter
- Facebook
- Email: contato@cocoaheads.com.br
- Channel do slack

Há alguma outra?

**Comment by barbosa** [comment]
Temos outros canais mas, como **formas de contato**, acho que são esses :+1:

**Comment by gfpoliva** [comment]
Então fechou!
