### ISSUE TITLE
Montar estrutura do Cloud Code

### ISSUE THREAD

**Issue by barbosa** [CocoaHeadsBrasil/CocoaHeadsApp#25]
![arquiteturacocoaheadsapp](https://cloud.githubusercontent.com/assets/235208/11453984/ead42124-95ec-11e5-825d-eb1a956cbcc8.png)

**Comment by barbosa** [comment]
closed via 75fa0bac47e7d7b86abb43c1ff158d276da09e80

**Comment by DougFischer** [comment]
Qual software foi usado para criar a imagem dessa estrutura ai?

**Comment by barbosa** [comment]
http://draw.io
