### ISSUE TITLE
Criar README.md

### ISSUE THREAD

**Issue by brunokoga** [CocoaHeadsBrasil/CocoaHeadsApp#3]
Precisamos criar o nosso README. Ele deve conter, _no mínimo_:
- Motivo do App existir;
- Quem somos nós;
- Quem pode colaborar;
- Estruturação do repositório (branches, tags, etc);
- Estruturação do código (folders, groups, etc);
- Explicação sobre decisões técnicas (gerenciar dependências, certificados, tecnologias utilizadas, etc);
- Workflow de colaboração;
- Copyrights;
- Agradecimentos;
- Links e formas de contato.

**Comment by barbosa** [comment]
Alguns desses items já foram colocados no README. Os outros, eu sugeriria criar uma issue específica para cada e fechar essa. Assim cada um pode ajudar um pouco.

**Comment by Viniciuscarvalho** [comment]
Dividir cada ponto que o Koga sugeriu, seria o melhor @barbosa ? E quais da lista você já fez?

**Comment by barbosa** [comment]
Sim, @Viniciuscarvalho 

Acho que essas duas já estão um pouco definidas:
- Estruturação do código (folders, groups, etc);
- Explicação sobre decisões técnicas (gerenciar dependências, certificados, tecnologias utilizadas, etc);

Se a gente achar depois que precisa melhorá-las, alteramos.

Então seria criar issues para cada um dos outros pontos. E fechar essa.

**Comment by barbosa** [comment]
Criei uma issue específica para cada item do README. 
Acho que fica melhor pra discutir separadamente sobre o que colocar em cada um. E ainda ajuda as pessoas a contribuírem em pequenas partes.
- Motivo do App existir (https://github.com/CocoaHeadsBrasil/CocoaHeadsApp/issues/17)
- Quem somos nós (https://github.com/CocoaHeadsBrasil/CocoaHeadsApp/issues/18)
- Quem pode colaborar (https://github.com/CocoaHeadsBrasil/CocoaHeadsApp/issues/19)
- Estruturação do repositório - branches, tags, etc (https://github.com/CocoaHeadsBrasil/CocoaHeadsApp/issues/20)
- Workflow de colaboração (https://github.com/CocoaHeadsBrasil/CocoaHeadsApp/issues/21)
- Copyrights (https://github.com/CocoaHeadsBrasil/CocoaHeadsApp/issues/22)
- Agradecimentos (https://github.com/CocoaHeadsBrasil/CocoaHeadsApp/issues/23)
- Links e formas de contato (https://github.com/CocoaHeadsBrasil/CocoaHeadsApp/issues/24)
