### ISSUE TITLE
Usar fastlane para criar linhas de build

### ISSUE THREAD

**Issue by igorcferreira** [CocoaHeadsBrasil/CocoaHeadsApp#39]
Seria interessante usar o fastlane no travis para gerenciar certificados, provisions e diferentes tipos de builds

**Comment by douglastaquary** [comment]
Vale a pena pegar essa agora? Posso pegar essa, visto que esses dois últimos meses venho configurando o `fastlane` e gerenciando `provisioning profiles` e `certificados` com `match`. Mas e a conta de `developer` do CH? Como fica?

**Comment by Viniciuscarvalho** [comment]
@douglasalexandre Acho que não vale a pena ver isso agora visto que não temos a definição da conta oficial do CH 👍

**Comment by douglastaquary** [comment]
@Viniciuscarvalho Opa, pois fechou! Vamos resolver então! Uma hora vai ter que ter mesmo, assim já `instiga` ainda mais a entrega do app. 😃 O que vcs acham @igorcferreira @barbosa ? Vamos resolver.

**Comment by barbosa** [comment]
@douglasalexandre a questão a ser resolvida é de onde virá a grana pra pagar a anuidade. O CocoaHeads hoje não faz dinheiro e nem é uma empresa. Então teríamos que resolver essas questões legais antes. O @DougFischer tinha uns pontos sobre isso. Mas ainda precisamos pensar com mais calma.

Apesar disso, acho que o setup e algumas lanes não dependem do fato de ter uma conta. Se quiser começar por ali, acho que é válido.

**Comment by douglastaquary** [comment]
Blz @barbosa. Acho que essa conta vai ter que ser rateada pra quem quiser colaborar, tipo uma vaquinha mesmo. Achava legal agente iniciar essa campanha! 👍

**Comment by lfarah** [comment]
Galera, Fastlane não é só a parte de build... Também podemos configurar o [Scan](https://github.com/fastlane/fastlane/tree/master/scan)
