### ISSUE TITLE
Lista de Funcionalidades

### ISSUE THREAD

**Issue by ezefranca** [CocoaHeadsBrasil/CocoaHeadsApp#4]
Issue aberta para discussão de funcionalidades. 

Funcionalidades: 
- Cadastro ? (usar login com github? facebook?)
- Calendario Geral (filtro por estados, datas) 
- Track dos seus eventos. (existe alguma API do Meetup?)
- Palestras anteriores (Slideshare, speakerdeck)
- Podcast (enviar push quando tive novo)
- Mapa de arredores dos eventos (estacionamento, bar, estacoes, pontos de onibus)
- Periscopes (ou streamings) de eventos rolando.
- Vagas de empregos / freelas (?)
- Sorteio de brindes nos eventos

**Comment by bguidolim** [comment]
Sugiro começarmos com um app simples, para que possamos lançar uma primeira versão o quanto antes.

Com isso em mente, sugiro as seguintes funcionalidades:
- Datas dos próximos eventos
- Palestras anteriores: Acesso aos slides e códigos
- Acesso aos episódios do Podcast

Não vejo necessidade de cadastro por não haver restrição de acesso ao dados, palestras, etc do CocoaHeads.

**Comment by marcelohd** [comment]
Não podemos esquecer de colocar os Videos

**Comment by Viniciuscarvalho** [comment]
Definir a estrutura de requisições da API do Meetup e Parse da aplicação

**Comment by barbosa** [comment]
Nesse caso o app só conhece o Parse, certo? E o Parse que chama a API do Meetup usando o Cloud Code lá, é isso?

**Comment by bguidolim** [comment]
Exato, pensei nisso quando sugeri usar o Parse.

**Comment by Viniciuscarvalho** [comment]
Por isso queria saber como seria essa chamada do Parse para a API do Meetup, pois tinham feito conectando diretamente a API.

**Comment by bguidolim** [comment]
No Parse utiliza-se o próprio SDK deles ao invés de chamadas REST. Quem fez as chamadas direto no Meetup?

**Comment by barbosa** [comment]
Já temos o Parse configurado com os dados vindo da API do CocoaHeads. Agora precisamos trocar as chamadas pra usar a SDK.

Para facilitar a primeira versão, vamos começar com:
- Datas dos próximos eventos
- Palestras anteriores: Acesso aos slides e códigos
- Acesso aos episódios do Podcast

Vou fechar essa issue para termos outras menores e mais específicas a seguir.
