### ISSUE TITLE
Substituir o Dynamics por RxSwift

### ISSUE THREAD

**Issue by igorcferreira** [CocoaHeadsBrasil/CocoaHeadsApp#47]
Acredito que o Dynamics possa ser substituído pela implementação do [RxSwift](https://github.com/ReactiveX/RxSwift). Utilizar o conceito de `reactive` and `observables`, além do gerenciamento de`KVO`, dessa biblioteca pode ajudar.

**Comment by brunokoga** [comment]
+1 aqui. Acho que isso faz sentido.

**Comment by barbosa** [comment]
Closed by #104 

Valeu @BrunoMazzo 🍻
