### ISSUE TITLE
Remover Parse do projeto

### ISSUE THREAD

**Issue by Viniciuscarvalho** [CocoaHeadsBrasil/CocoaHeadsApp#48]
- Observar onde o Parse está no projeto e trocar por dados mockado;
- Remover instruções do Parse no Readme;

**Comment by barbosa** [comment]
Hoje não tem nenhuma view sendo preenchida com os dados vindo do Parse. Não precisa nem trocar por dados mockados. Basta tirar as referências ao SDK.

**Comment by igorcferreira** [comment]
Acho que já podemos pensar nas models, formatar os json esperados e usar esses dados para construir os mocks (O que é bom até para testes).

**Comment by Viniciuscarvalho** [comment]
Melhor ainda então @barbosa, se remover as referências não vai ter impacto na aplicação hoje :) Vou fazer isso.

**Comment by marcelohd** [comment]
Remover diretório CloudeCode se nao me engano. era parte do parse
