### ISSUE TITLE
Links para vídeos / podcasts

### ISSUE THREAD

**Issue by igorcferreira** [CocoaHeadsBrasil/CocoaHeadsApp#5]
Acredito que o app possa conter links para:
- Vídeos de edições anteriores
- Áudio dos podcasts

**Comment by diegoventura** [comment]
Trabalhei num app de música...posso fazer o player do podcast

**Comment by barbosa** [comment]
Acho que podemos dividir essa issue em duas. Uma para cada feature sugerida.

Vou fechar e criar as novas com as mesmas tags.
