### ISSUE TITLE
Criar modelos relacionados às informações disponíveis no servidor

### ISSUE THREAD

**Issue by igorcferreira** [CocoaHeadsBrasil/CocoaHeadsApp#50]
Chamadas do servidor:

[Todas](http://www.cocoaheads.com.br/agendas/todas.json)
[Agendas](http://www.cocoaheads.com.br/agendas.json)
[Cidades](http://www.cocoaheads.com.br/cidades.json)
[Podcasts](http://www.cocoaheads.com.br/podcasts.json)
[Videos](http://www.cocoaheads.com.br/videos.json)

**Comment by Viniciuscarvalho** [comment]
O backend está pronto com essas informações todas? A retirada das informações conectadas direta do Meetup, serão feitas aqui certo?
