### ISSUE TITLE
Indagação sobre a seção "Quem Somos"

### ISSUE THREAD

**Issue by barbosa** [CocoaHeadsBrasil/CocoaHeadsApp#54]
Estava lendo essa frase:

> Promovemos Talks e Palestras de até 20 minutos dadas por membros do grupo local ou de convidados especiais e é lógico, comidas, bebidas e snacks ao final.

... e pensando se atualmente condiz com a nossa realidade. Não sei se é verdade que em todas as cidades que nossos talks acontecem, eles são de até 20 minutos (acredito que muitos não são). Além disso, acho que colocar `comidas, bebidas e snacks` pode passar uma propaganda enganosa, dado que nem todo evento conseguimos alguém ajudando com o coffee.

**Comment by fwigorcferreira** [comment]
Acredito que a descrição poderia acabar antes dessa frase. O CocoaHeads já fez eventos em São Paulo onde as palestras eram bem maiores de 20 minutos. Tem o fato da comida/bebida que você levantou e além disso, atualmente, o CocoaHeads tem as conversas do Slack, Podcast e outras iniciativas.

**Comment by barbosa** [comment]
Acho que vale dar uma melhorada nesse texto, apesar de ter sido retirado do site do CocoaHeads. Aproveitamos inclusive para trocar lá também.

Quer bolar alguma coisa, @Viniciuscarvalho ?

**Comment by Viniciuscarvalho** [comment]
Vou procurar melhorar esse Quem somos, mais tarde dou uma olhada @barbosa

**Comment by barbosa** [comment]
@Viniciuscarvalho beleza. 

Depois a gente pede pro JP (ou alguém que tenha acesso) para trocar no site também.
