### ISSUE TITLE
Adicionar VTAcknowledgementsViewController pod ao projeto

### ISSUE THREAD

**Issue by brunogb** [CocoaHeadsBrasil/CocoaHeadsApp#55]
Seria muito interessante mostrar no App quais tecnologias openSource estamos usando.
E na verdade é bem simples fazer isso.

Basta configurar o final do Podfile com:

``` ruby
pod 'VTAcknowledgementsViewController'
#copy the acknowledgements file when installing news pods
post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods/Pods-acknowledgements.plist', 'Pods-acknowledgements.plist', :remove_destination => true)
end
```

E depois importar esse arquivo gerado no projeto. Dai basta exibir o `VTAcknowledgementsViewController` como quisermos.

Fonte da idéia: [trySwift! Podfile](https://github.com/NatashaTheRobot/trySwiftApp/blob/master/Podfile)

**Comment by igorcferreira** [comment]
:+1:

**Comment by barbosa** [comment]
A diferença dele para o [CocoaPods Acknowledgements](https://github.com/CocoaPods/cocoapods-acknowledgements) é que um disponibiliza uma VC pra vc chamar como quiser dentro da aplicação enquanto o outro gera um plist que vai ser disponibilizado via `Settings.bundle` e apresentado no settings do iOS?

Ou tem algo mais além disso?

cc @marcelofabri

**Comment by igorcferreira** [comment]
Gostaria de adicionar aqui, que também existe o projeto [CPDAcknowledgements](https://github.com/cocoapods/CPDAcknowledgements) para construção dessa `UIViewController` para listar os pods.

**Comment by marcelofabri** [comment]
@barbosa O plugin (https://github.com/CocoaPods/cocoapods-acknowledgements) copia automaticamente o plist pro projeto e suporta tanto o formato do `Settings.bundle` quanto do https://github.com/cocoapods/CPDAcknowledgements

**Comment by fwigorcferreira** [comment]
Devemos usar o `VTAcknowledgementsViewController` ou a combinação de `cocoapods-acknowledgements` e `CPDAcknowledgements`?

**Comment by igorcferreira** [comment]
Devemos usar o `VTAcknowledgementsViewController` ou a combinação de `cocoapods-acknowledgements` e `CPDAcknowledgements`.

Eu acho interessante usar o `cocoapods-acknowledgements` pela possibilidade de listar as libs no `Settings.bundle`

**Comment by barbosa** [comment]
Vamos com ele então.

**Comment by Viniciuscarvalho** [comment]
Tava lendo ontem sobre o `cocoapods-acknowledgements`, me pareceu o mais limpo digamos assim.

**Comment by igorcferreira** [comment]
Eu irei fechar esse issue e criar um novo com as instruções para criação da listagem de libs com `cocoapods-acknowledgements` e `CPDAcknowledgements`.

**Comment by igorcferreira** [comment]
Esta issue foi fechada em favorecimento da issue #69.
