### ISSUE TITLE
Funções administrativas (sugestão)

### ISSUE THREAD

**Issue by ezefranca** [CocoaHeadsBrasil/CocoaHeadsApp#6]
Para os organizadores do evento:
- "Lista de presença". (Pra nao precisar de uma lista fisica, assinar e etc)
-  Emissão de certificado? (Em SP o pessoal fornece).
-  Sorteio - Agilizar os sorteios que tem as vezes.

**Comment by gfpoliva** [comment]
A lista de presença pode ser implementando iBeacon. Uma vez que o aparelho do palestrante age como um beacon e cria uma range, todos que estão participando do evento entram nessa região e a partir daí da pra fazer % de presença e outros tipos de tracks que podem ser interessantes para levantar dados e tomar decisões. Se precisarem de alguém pra implementar essa parte, estou à disposição.

**Comment by igorcferreira** [comment]
Esta Issue foi divida nos três points listados, através das Issues:
#63 - Lista de presença
#64 - Emissão de certificado
#65 - Sorteio
