### ISSUE TITLE
Applicar ferramenta de Lint

### ISSUE THREAD

**Issue by igorcferreira** [CocoaHeadsBrasil/CocoaHeadsApp#62]
Acho que vale a pena criar/configurar um [SwiftLint](https://github.com/realm/SwiftLint) no projeto.

**Comment by barbosa** [comment]
:+1:

**Comment by Viniciuscarvalho** [comment]
Que irado, não conhecia :+1:

**Comment by Viniciuscarvalho** [comment]
Vou sugerir algumas `rules`que tinha visto no repositório,

**ClosingBrace** - "Closing brace with closing parenthesis " + "should not have any whitespaces in the middle."
**ConditionalBindingCascade** - "Repeated `let` statements in conditional binding cascade should be avoided."
**EmptyCount** - "Prefer checking `isEmpty` over comparing `count` to zero."
**ForceCast** - "Force casts should be avoided."
**ForceTry** - "Force tries should be avoided."
**FunctionParamenterCount** - "Number of function parameters should be low."
**LeadingWhitesSpace** - "Files should not contain leading whitespace."
**LegacyConstant** - "Struct-scoped constants are preferred over legacy global constants."
**LegacyConstruct** - "Swift constructors are preferred over legacy convenience functions."
**OperatorFunctionWhitespace** - "Operators should be surrounded by a single whitespace when defining them."
**ReturnArrowWhitespace** - "Return arrow and return type should be separated by a single space or on a " +"separate line."
**VariableName** - "Variable names should only contain alphanumeric characters and " +
          "start with a lowercase character or should only contain capital letters. "

Acredito que essas são boas pra gente iniciar, o que acham?

**Comment by barbosa** [comment]
Tem alguma forma de verificar o que é cada uma? Lendo aqui, dá até pra ter uma ideia do que são algumas. Mas outras, não.

**Comment by igorcferreira** [comment]
Acho válido, @Viniciuscarvalho, editar seu comentário e colocar o link para o arquivo de cada rule. Assim a pessoa pode ler a descrição

**Comment by Viniciuscarvalho** [comment]
Coloquei uma descrição básica do que é cada um @igorcferreira @barbosa

**Comment by barbosa** [comment]
@Viniciuscarvalho Acho que essa descrição de `EmptyCount` está errada, não?

Tirando isso, acho que podemos começar com essas. 

Você vai pegar essa issue? Acho importante termos ela implementada o quanto antes. Para evitar ter que corrigir um monte de coisas depois que o lint estiver sendo executado.

**Comment by Viniciuscarvalho** [comment]
@barbosa eu peguei a descrição da documentação do lint sobre o `EmptyCount``

E quanto a implementação, eu não sei, joguei alguns dados que poderia conter no Lint, nunca fiz algo parecido e posso comprometer o desenvolvimento desta funcionalidade.

**Comment by igorcferreira** [comment]
@Viniciuscarvalho a descrição do **EmptyCount** realmente está errada. A descrição correta é:

```
"Prefer checking `isEmpty` over comparing `count` to zero."
```

**Comment by Viniciuscarvalho** [comment]
@igorcferreira @barbosa corrigido a descrição de `EmptyCount` :+1:

**Comment by igorcferreira** [comment]
@Viniciuscarvalho Se quiser, posso pegar para fazer essa task

**Comment by Viniciuscarvalho** [comment]
Beleza @igorcferreira , é sua então :+1: Ainda não to 100% ou ter muito o domínio da ferramenta.

**Comment by igorcferreira** [comment]
A configuração crua do SwiftLint gera mais de 999 warnings e 117 erros. Eu vou ver quais são relevantes e quais não são. Baseado nos que faz sentido, eu deixarei o mínimo de regras, refatorar o app e, depois, precisamos decidir quais regras serão reaplicadas.

![SwiftLint warnings](https://dl.dropboxusercontent.com/u/16397611/SwiftLint.png)

**Comment by Viniciuscarvalho** [comment]
Caramba! Acredita que apenas aquelas regras que listei sejam as mais válidas para o momento @igorcferreira?

**Comment by igorcferreira** [comment]
Tem algumas outras regras que fazem sentido. Como nome de variável, _legacy constructor_ (não sei traduzir isso para português), documentação, TODO/FIXME, nesting... Entre outras.
