### ISSUE TITLE
Adicionar cocoapods-acknowledgements e CPDAcknowledgements ao projeto

### ISSUE THREAD

**Issue by igorcferreira** [CocoaHeadsBrasil/CocoaHeadsApp#69]
Conforme a discussão feita no issue #55 ficou decidido a utilização do plugin [cocoapods-acknowledgements](https://github.com/CocoaPods/cocoapods-acknowledgements) e da bibloteca [CPDAcknowledgements](https://github.com/cocoapods/CPDAcknowledgements) para listar as bibliotecas usadas.

**Comment by BrunoMazzo** [comment]
Opa, beleza?
Queria começar a ajudar então tentei fazer essa task mas encontrei alguns problemas.
Não sei se eu estou fazendo alguma coisa errada, mas pelo o que eu vi aqui, o CPDAcknowledgements esta com alguns bugs, além disso, o formato de arquivo que ele esta lendo não o mesmo que o  cocoapods-acknowledgements gera (ele precisa que adicione um CPD na frente de todas as chaves). Fix um PR no  CPDAcknowledgements com algumas alterações mas não sei se ele será aceito, a lib esta a um bom tempo inativa. Enquanto isso posso subir só o Settings? Ou aponto para o meu fork? Troco de Lib?

**Comment by igorcferreira** [comment]
@BrunoMazzo Desculpe pela demora na resposta. Eu acredito que não vale a pena fazer só o Settings e depois trocar de lib. Você pode apontar para seu fork. Ou, caso tenha outra recomendação de lib, usar outra.
