### ISSUE TITLE
Fluxo inicial aplicação

### ISSUE THREAD

**Issue by Viniciuscarvalho** [CocoaHeadsBrasil/CocoaHeadsApp#71]
- Definição das primeiras telas do aplicativos;
- Implementação de funcionalidades;
- Mockup das telas
  ![fluxo-inicial-app](https://cloud.githubusercontent.com/assets/4513004/13581473/cf7f3ae8-e485-11e5-8b2c-fc2b6ebb61b3.png)

**Comment by igorcferreira** [comment]
Sugestão: Criar 1 issue para cada tela e 1 para a estrutura de navegação. Assim, fica mais fácil de sugerir mudanças e paralelizar o trabalho de telas

**Comment by barbosa** [comment]
Concordo com o Igor. Senão essa issue vai ficar muito grande.

Também seria melhor ter as telas que vamos implementar de fato. Já discutimos algumas coisas que mudaram desde essa versão da imagem.

**Comment by Viniciuscarvalho** [comment]
Vou desmembrar em outras issues.

E fiz as modificações de cores e telas que iremos realmente implementar nesta versão 0.1 @barbosa @igorcferreira
