### ISSUE TITLE
Tela inicial

### ISSUE THREAD

**Issue by Viniciuscarvalho** [CocoaHeadsBrasil/CocoaHeadsApp#72]
- Criar segmented control direcionando para todos de sua cidade e chapters de diferentes cidades;
- Listar todos os eventos;

![home-appch](https://cloud.githubusercontent.com/assets/4513004/13622524/1094031c-e57e-11e5-9f69-83b28ab8695c.png)

**Comment by barbosa** [comment]
Para a primeira versão, tiraria a busca e o "perto de você".

Acho melhor trocar o texto dessa tab para "Eventos" ou "Meetups" também. "Home" não diz muita coisa.

**Comment by Viniciuscarvalho** [comment]
Acha que o melhor seria Eventos? @barbosa

**Comment by barbosa** [comment]
Acho que sim :+1:

**Comment by Viniciuscarvalho** [comment]
Atualizado os textos da tela de eventos.

**Comment by Viniciuscarvalho** [comment]
Posso atualizar os Xibs, com e reformular tais classes?

**Comment by igorcferreira** [comment]
@Viniciuscarvalho Eu acredito que sim

**Comment by igorcferreira** [comment]
Se você for começar a construir o relacionamento de `Views` e `Models`, recomendo ler o texto do Diogo no EquinociOS e também a talk dada pela Natasha no [do{iOS} 2015](https://realm.io/news/doios-natasha-murashev-protocol-oriented-mvvm/)

**Comment by Viniciuscarvalho** [comment]
Pode deixar @igorcferreira

**Comment by Viniciuscarvalho** [comment]
Estou com uma dúvida na implementação do Model de `Events`, o que vai ser extraído do nosso backend?

**Comment by barbosa** [comment]
@Viniciuscarvalho não entendi a dúvida.

**Comment by Viniciuscarvalho** [comment]
Me expressei mal @barbosa, a minha dúvida é, o que iremos colocar no Model de `Events`?

Por exemplo:

`struct Events {
    let id: Int
    let name: String
    .....
}`

Entendeu?

**Comment by barbosa** [comment]
@Viniciuscarvalho vc diz criar o model? Pq se for, ele já existe:
https://github.com/CocoaHeadsBrasil/CocoaHeadsApp/blob/master/CocoaHeadsApp/CocoaHeadsApp/Classes/Model/Event.swift

**Comment by Viniciuscarvalho** [comment]
Viush, então o meu fork deve estar desatualizado... E tinha feito várias modificações :/

**Comment by barbosa** [comment]
Faz rebase aí então.

**Comment by Viniciuscarvalho** [comment]
Beleza, vou perder minhas modificações né?

**Comment by barbosa** [comment]
@Viniciuscarvalho perde não. 

O rebase vai aplicar as modificações no seu branch local antes dos commits que vc fez. Depois disso, o git vai colocar seus commits no topo. Aí sim que pode dar os conflitos. Mas é mais fácil resolver pq vc sabe o que vc fez.

**Comment by Viniciuscarvalho** [comment]
Resolvido :) Continuar aqui com a programação da tela normalmente, valeu @barbosa e @igorcferreira !

**Comment by barbosa** [comment]
Vou desenhar uma tela com o que pensei e colo aqui.

**Comment by Viniciuscarvalho** [comment]
Mudança dos nomes das classes de `MeetupEvent`, para `Events`, para deixar algo mais geral e não só dependendo da API do Meetup.

**Comment by Viniciuscarvalho** [comment]
Mudança na tela inicial para apresentar a lista de eventos marcados como favoritos por estados.

**Comment by barbosa** [comment]
Fechando pois novas issues serão criadas a partir dessa.
