### ISSUE TITLE
Tela detalhes do evento

### ISSUE THREAD

**Issue by Viniciuscarvalho** [CocoaHeadsBrasil/CocoaHeadsApp#74]
- Mostrar descrição do evento;
- Palestrantes com descrição dos assuntos;
- Área para inscrição ( RSVP );

![detalhes-appch](https://cloud.githubusercontent.com/assets/4513004/13622564/4fa0db3e-e57e-11e5-8a1f-164e6ae7282f.png)

**Comment by barbosa** [comment]
Eu gostei das informações dessa tela. Mas acho que poderíamos ter um apelo visual maior. Como foto do palestrante, por exemplo.

Acho que a app do try Swift é um exemplo de algo que gostaria mais de ver a gente fazendo aqui.

**Comment by Viniciuscarvalho** [comment]
Vou tentar dar uma melhorada visualmente nesta tela, peguei algumas ideais do app do Try Swift.

**Comment by Viniciuscarvalho** [comment]
Atualizado a imagem de detalhes.

**Comment by barbosa** [comment]
Fechando. Ver #95
