### ISSUE TITLE
Adicionar ferramenta de tracking de usuários e crashes

### ISSUE THREAD

**Issue by igorcferreira** [CocoaHeadsBrasil/CocoaHeadsApp#77]
Eu acho relevante a utilização de uma ferramenta como [Fabric](https://get.fabric.io/) ou [Hockey](http://hockeyapp.net/). Eu tenho mais familiaridade com o Fabric e eu acho que o acompanhamento de crash free sessions e detalhamento de erros muito bons. Possível, até, enviar soft errors para o servidor e manter tracking disso.

**Comment by miguelarauj1o** [comment]
@igorcferreira, alguém trabalhando nesse? Eu posso resolver esta aqui.

**Comment by Viniciuscarvalho** [comment]
Olá @miguelarauj1o, não tem ninguém trabalhando nesta issue não, se quiser adicionar o Fabric/Crashlytics, só assinar a issue e começar 🚀

**Comment by miguelarauj1o** [comment]
@Viniciuscarvalho, me coloca ai, vou resolver isso! :)

**Comment by Viniciuscarvalho** [comment]
Tenho que te colocar como colaborador do repositório @miguelarauj1o , você pode fazer isso @barbosa ?

**Comment by miguelarauj1o** [comment]
Eita, não precisa se n quiser. por um momento pensei que dava pra dar assign ser participar do projeto.
Deixa assim msm, eu dou um PR e vcs fecham quando achar apropriado.

**Comment by Viniciuscarvalho** [comment]
Beleza, quando tiver ok a gente faz o review no PR e te passa o feedback.

**Comment by miguelarauj1o** [comment]
Meu MacBook está com a película de proteção da tela descascando.
Deixe na [iTown ](http://www.itown.com.br/)desde o começo da semana e o prazo para pegar é, pelo menos, **15 dias**.
Tive sorte que é um problema de fábrica e não precisou de garantia, nem nota fiscal. Aparentemente, isto está aparecendo em alguns MacBooks Pro com Retina.

@Viniciuscarvalho. Logo, eu vou demorar para resolver esta issue, caso alguém não resolva antes.

**Comment by Viniciuscarvalho** [comment]
Sem problemas @miguelarauj1o , não está impedindo o desenvolvimento de outras issues :D

**Comment by lfarah** [comment]
@Viniciuscarvalho @miguelarauj1o Eu estou bem feliz com o [Bugsee](bugsee.com) ultimamente
