### ISSUE TITLE
Abstração da API

### ISSUE THREAD

**Issue by Viniciuscarvalho** [CocoaHeadsBrasil/CocoaHeadsApp#79]
Qual lib ou vamos utilizar NSURLSession para fazer o tratamento dos JSONs da nossa API?
- Moya;
- Alamofire;
- ObjectMapper;
- NSURLSession;
- Outra?

**Comment by igorcferreira** [comment]
Acho desnecessário o uso do `ObjectMapper`, dado a estrutura de modelos que temos. Não acredito que precisamos trabalhar com `NSURLSession`, dado os métodos públicos ainda não serem "Swiftly"!

**Comment by igorcferreira** [comment]
Acho desnecessário o uso do `ObjectMapper`, dado a estrutura de modelos que temos. Não acredito que precisamos trabalhar com `NSURLSession`, dado os métodos públicos ainda não serem "Swiftly"!

Por fim, acredito que podemos utilizar `Alamofire` ou `Moya`. Não tenho experiência/contato com o Moya, mas o @brunogb recomendou o uso.

**Comment by Viniciuscarvalho** [comment]
Nunca utilizei o `Moya` também, por mim eu gostaria que utilizássemos o `Alamofire`.

**Comment by unnamedd** [comment]
Pessoal, vale lembrar que o **Moya** é uma camada construída em cima do **Alamofire**, se forma que é redundante falar em usar **Moya** e **Alamofire**.

**Comment by FelipeCardoso89** [comment]
Eu já utilizei o Moya e recomendo. Fica bem facil ligar com os endpoints,
além de facilitar a organização do cliente da API. Acho que facilita também
os testes unitários uma vez que é possível fazer o mock chamadas usando o
Moya. :)
Em sex, 29 de abr de 2016 às 22:40, Thiago Holanda notifications@github.com
escreveu:

**Comment by Viniciuscarvalho** [comment]
Então vamos de Moya para o parse das chamadas JSONs, correto?
https://github.com/Moya/Moya
