### ISSUE TITLE
Configurar Travis CI

### ISSUE THREAD

**Issue by barbosa** [CocoaHeadsBrasil/CocoaHeadsApp#9]

**Comment by barbosa** [comment]
Parece que ainda não tem suporte:

> Apple released Xcode 7 and the iOS 9 SDK at WWDC. Everyone is excited to test their apps against the latest SDKs and Swift 2.0, and we are working hard to get Xcode 7 ready for you to test on.

http://next.travis-ci.com/

**Comment by igorcferreira** [comment]
@barbosa Você pode associar essa task para mim? Eu não tenho permissão para mudar o "Assignee".
